export const defaultShapes = [
    {
        id: 1,
        backgroundColor: 'rgb(239, 239, 239)',
        height: '50px',
        width: '100px',
        padding: '0px',
        borderStyle: 'solid',
        borderColor: 'rgb(204, 204, 204)',
        borderWidth: '1px',
        borderRadius: '0px',
        boxShadow: 'rgb(0, 0, 0) 0px 0px 0px',
        left: '0px',
        top: '0px',
        right: '0px',
    },
    {
        id: 2,
        backgroundColor: 'rgb(239, 239, 239)',
        height: '100px',
        width: '100px',
        padding: '0px',
        borderStyle: 'solid',
        borderColor: 'rgb(204, 204, 204)',
        borderWidth: '1px',
        borderRadius: '100px',
        boxShadow: 'rgb(0, 0, 0) 0px 0px 0px',
        opacity: 1,
        left: '0px',
        top: '0px',
        right: '0px',
    },
    {
        id: 3,
        tag: 'div',
        backgroundColor: 'rgb(239, 239, 239)',
        height: '100px',
        width: '100px',
        padding: '0px',
        borderStyle: 'solid',
        borderColor: 'rgb(204, 204, 204)',
        borderWidth: '1px',
        borderRadius: '0px',
        boxShadow: 'rgb(0, 0, 0) 0px 0px 0px',
        opacity: 1,
        left: '0px',
        top: '0px',
        right: '0px',
    },
    {
        id: 4,
        backgroundColor: 'rgb(54, 207, 201)',
        height: '50px',
        width: '100px',
        padding: '0px',
        borderStyle: 'none',
        borderColor: 'rgb(0, 0, 0)',
        borderWidth: '0px',
        borderRadius: '0px',
        boxShadow: 'rgb(0, 0, 0) 0px 0px 0px',
        opacity: 1,
        left: '0px',
        top: '0px',
        right: '0px',
    },
    {
        id: 5,
        backgroundColor: 'rgb(64, 169, 255)',
        height: '100px',
        width: '100px',
        padding: '0px',
        borderStyle: 'none',
        borderColor: 'rgb(0, 0, 0)',
        borderWidth: '0px',
        borderRadius: '100px',
        boxShadow: 'rgb(0, 0, 0) 0px 0px 0px',
        opacity: 1,
        left: '0px',
        top: '0px',
        right: '0px',
    },
    {
        id: 6,
        backgroundColor: 'rgb(146, 84, 222)',
        height: '100px',
        width: '100px',
        padding: '0px',
        borderStyle: 'solid',
        borderColor: 'rgb(204, 204, 204)',
        borderWidth: '5px',
        borderRadius: '0px',
        boxShadow: 'rgb(0, 0, 0) 0px 0px 0px',
        opacity: 1,
        left: '0px',
        top: '0px',
        right: '0px',
    },
]
