export const defaultTemplates = [
    {
        text: '大标题',
        fontSize: '30px',
        tag: 'h2',
        fontWeight: 'bold',
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
        id: 1,
    },
    {
        text: '楷体副标题',
        tag: 'p',
        id: 2,
        fontFamily: 'KaiTi',
        fontSize: '20px',
        fontWeight: 'bold',
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: '正文内容',
        fontSize: '14px',
        tag: 'p',
        fontWeight: 'normal',
        id: 3,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: '宋体正文内容',
        fontFamily: 'SimSun',
        fontSize: '14px',
        tag: 'p',
        fontWeight: 'normal',
        id: 4,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'Arial style',
        fontFamily: 'Arial',
        fontSize: '14px',
        tag: 'p',
        fontWeight: 'normal',
        id: 5,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'Comic Sans',
        fontFamily: 'Comic Sans MS',
        fontSize: '14px',
        tag: 'p',
        fontWeight: 'normal',
        id: 6,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'Courier New',
        fontFamily: 'Courier New',
        fontSize: '14px',
        tag: 'p',
        id: 7,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'Times New Roman',
        fontFamily: 'Times New Roman',
        fontSize: '14px',
        tag: 'p',
        id: 8,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'Roboto-Bold',
        fontFamily: 'Roboto-Bold',
        fontSize: '14px',
        tag: 'p',
        id: 9,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'Roboto-Medium',
        fontFamily: 'Roboto-Medium',
        fontSize: '14px',
        tag: 'p',
        id: 10,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'Roboto-Medium-Italic',
        fontFamily: 'Roboto-Medium-Italic',
        fontSize: '14px',
        tag: 'p',
        id: 11,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'Roboto-Medium-Italic',
        fontFamily: 'Roboto-Medium-Italic',
        fontSize: '14px',
        tag: 'p',
        id: 12,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'YujiMai',
        fontFamily: 'YujiMai',
        fontSize: '14px',
        tag: 'p',
        id: 13,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'ZhiMangXing',
        fontFamily: 'ZhiMangXing',
        fontSize: '14px',
        tag: 'p',
        id: 14,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'ZCOOLXiaoWei',
        fontFamily: 'ZCOOLXiaoWei',
        fontSize: '14px',
        tag: 'p',
        id: 15,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'ZCOOLQingKeHuangYou',
        fontFamily: 'ZCOOLQingKeHuangYou',
        fontSize: '14px',
        tag: 'p',
        fontWeight: 'normal',
        id: 16,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'DancingScript',
        fontFamily: 'DancingScript',
        fontSize: '14px',
        tag: 'p',
        id: 17,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'LongCang',
        fontFamily: 'LongCang',
        fontSize: '14px',
        tag: 'p',
        id: 18,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'MaShanZheng',
        fontFamily: 'MaShanZheng',
        fontSize: '14px',
        tag: 'p',
        id: 19,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
    {
        text: 'OpenSans',
        fontFamily: 'OpenSans',
        fontSize: '14px',
        tag: 'p',
        id: 20,
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },

    //一个按钮
    {
        text: '按钮',
        backgroundColor: '#1890ff',
        color: '#fff',
        fontSize: '16px',
        fontWeight: 'bold',
        textAlign: 'center',
        paddingTop: '8px',
        paddingBottom: '8px',
        paddingLeft: '20px',
        paddingRight: '20px',
        borderRadius: '4px',
        tag: 'button',
        id: 22,
        height: '36px',
    },
    {
        text: '链接内容',
        color: '#5390ef',
        textDecoration: 'underline',
        tag: 'a',
        id: 21,
        fontSize: '14px',
        paddingTop: '0px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        height: '36px',
    },
]
